### ISSUE TITLE
Setup CLI functionality for i18n-check

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/i18n-check#4]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/i18n-check/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](.github/CODE_OF_CONDUCT.md)

### Description

The basic idea of `i18n-check` is that it will function as a CLI. We should leverage `argparse` to bring in arguments for the CLI, but the main usage of the package will not be argument based. Rather we want the user to be able to do the following in the command line:

```bash
i18n-check
```

From here the CLI would check an `i18n_check_config.yaml` file for the arguments needed for the checks, which would then be ran. Arguments for the CLI would be:

- `-h` / `--help` (we'd need to change the first letter of the help message to being capitalized)
- `-v` / `--version` (check the version of the CLI)
- `-u` / `--upgrade` (upgrades to the latest version)
- `-cc` / `--create-config` (an interactive prompt to then create a config file at the end)
    - This would include placeholders to suggest common structures

The `-cc` functionality would also automatically be ran if the user tries to use the check without a config file.

### Contribution

Happy to discuss this and review the work when a PR is opened! 🚀

**Comment by andrewtavis** [comment]
CC @OmarAI2003 👋 Let me know if there are questions on the above! :) Great to have you in the sync! 😊

**Comment by andrewtavis** [comment]
I think that these changes can go in a `scr/i18n-check/cli.py` file, and we can follow the `src/scribe_data/cli/main.py` for this :)

**Comment by OmarAI2003** [comment]
> CC @OmarAI2003 👋 Let me know if there are questions on the above! :) Great to have you in the sync! 😊

Hi @andrewtavis ,of course! I've got a lot of questions, and I'm excited to start on this. However, I have three exams left, so I’ll begin working on this seriously by the 7th of January.

Also, ideally, I should do the test related #2 issue before starting this right?

**Comment by andrewtavis** [comment]
You can work on this or #2 beforehand, @OmarAI2003 :) Whatever works best for you 😊 Let's check in in the new year after your tests, and good luck on them! 😊

**Comment by andrewtavis** [comment]
Quick note here while I'm thinking about it, @OmarAI2003 :) We should try to figure out a way for `directories-to-skip` to allow for some directories to be allowed for some checks and not for others. Maybe some of these should be based on the check level, so the YAML could be something like:

```yaml
src-dir: frontend
i18n-dir: frontend/i18n
i18n-src: frontend/i18n/en.json

checks:
  - all:
    active: true
    skip: [frontend/node_modules]
  - invalid-keys:
    skip: []
  - key-identifiers:
    skip: []
  - unused-keys:
    skip: []
  - non-source-keys:
    skip: []
  - repeat-values:
    skip: []

file-types-to-check: [.ts, .js]
warn-on-nested-i18n-src: true
```

I.e. there would be `all` that would effect all checks for global arguments, and then we could do check level assignments as well? Let me know what you think :) Open to suggestions!
